--
-- PostgreSQL database dump
--

\restrict KmCM8FPgidghe18X8DtOycQHMCOMvpH5wF6gUZWW7bUDeRwCE8fmuqghZeSHQhf

-- Dumped from database version 15.18 (Debian 15.18-1.pgdg13+1)
-- Dumped by pg_dump version 15.18 (Debian 15.18-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: cliente; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cliente (
    cliente_id character varying(255) NOT NULL,
    contrasena character varying(255),
    estado boolean,
    id bigint NOT NULL
);


ALTER TABLE public.cliente OWNER TO postgres;

--
-- Name: cuenta; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cuenta (
    id bigint NOT NULL,
    estado boolean,
    numero_cuenta character varying(255) NOT NULL,
    saldo_disponible double precision NOT NULL,
    saldo_inicial double precision NOT NULL,
    tipo_cuenta character varying(255) NOT NULL,
    cliente_id bigint NOT NULL
);


ALTER TABLE public.cuenta OWNER TO postgres;

--
-- Name: cuenta_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cuenta ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cuenta_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: movimiento; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.movimiento (
    id bigint NOT NULL,
    fecha date NOT NULL,
    saldo double precision NOT NULL,
    tipo_movimiento character varying(255) NOT NULL,
    valor double precision NOT NULL,
    cuenta_id bigint NOT NULL
);


ALTER TABLE public.movimiento OWNER TO postgres;

--
-- Name: movimiento_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.movimiento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movimiento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: persona; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.persona (
    id bigint NOT NULL,
    direccion character varying(255),
    edad integer,
    genero character varying(255),
    identificacion character varying(255) NOT NULL,
    nombre character varying(255) NOT NULL,
    telefono character varying(255)
);


ALTER TABLE public.persona OWNER TO postgres;

--
-- Name: persona_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.persona ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.persona_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: cliente; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cliente (cliente_id, contrasena, estado, id) FROM stdin;
joselema	1234	t	2
juanosorio	12345	t	27
marianelamontalvo	5678	t	28
\.


--
-- Data for Name: cuenta; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cuenta (id, estado, numero_cuenta, saldo_disponible, saldo_inicial, tipo_cuenta, cliente_id) FROM stdin;
10	t	585545	1000	1000	Corriente	2
6	t	478758	1425	2000	Ahorros	2
7	t	225487	700	100	Corriente	28
8	t	495878	150	0	Ahorros	27
9	t	496825	0	540	Ahorros	28
\.


--
-- Data for Name: movimiento; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.movimiento (id, fecha, saldo, tipo_movimiento, valor, cuenta_id) FROM stdin;
8	2026-06-05	1425	Retiro	-575	6
9	2026-06-05	700	Deposito	600	7
10	2026-06-05	150	Deposito	150	8
11	2026-06-05	0	Retiro	-540	9
\.


--
-- Data for Name: persona; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.persona (id, direccion, edad, genero, identificacion, nombre, telefono) FROM stdin;
2	Otavalo sn y principal	310	Masculino	1234567890	Jose Lema	098254785
27	13 junio y Equinoccial	25	Masculino	78945682	Juan Osorio	98874587
28	Amazonas y NNUU	25	Femenino	1002255896	Marianela Montalvo	097548965
\.


--
-- Name: cuenta_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cuenta_id_seq', 10, true);


--
-- Name: movimiento_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.movimiento_id_seq', 11, true);


--
-- Name: persona_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.persona_id_seq', 30, true);


--
-- Name: cliente cliente_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cliente_pkey PRIMARY KEY (id);


--
-- Name: cuenta cuenta_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuenta
    ADD CONSTRAINT cuenta_pkey PRIMARY KEY (id);


--
-- Name: movimiento movimiento_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movimiento
    ADD CONSTRAINT movimiento_pkey PRIMARY KEY (id);


--
-- Name: persona persona_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.persona
    ADD CONSTRAINT persona_pkey PRIMARY KEY (id);


--
-- Name: cliente ukkou3iuyp26clwwj9m5d0e6t0l; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT ukkou3iuyp26clwwj9m5d0e6t0l UNIQUE (cliente_id);


--
-- Name: cuenta ukpj7ncg765kt4klndu25bwbwe4; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuenta
    ADD CONSTRAINT ukpj7ncg765kt4klndu25bwbwe4 UNIQUE (numero_cuenta);


--
-- Name: persona ukr5vsms84ih2viwd6tatk9o5pq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.persona
    ADD CONSTRAINT ukr5vsms84ih2viwd6tatk9o5pq UNIQUE (identificacion);


--
-- Name: movimiento fk4ea11fe7p3xa1kwwmdgi9f2fi; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movimiento
    ADD CONSTRAINT fk4ea11fe7p3xa1kwwmdgi9f2fi FOREIGN KEY (cuenta_id) REFERENCES public.cuenta(id);


--
-- Name: cuenta fk4p224uogyy5hmxvn8fwa2jlug; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuenta
    ADD CONSTRAINT fk4p224uogyy5hmxvn8fwa2jlug FOREIGN KEY (cliente_id) REFERENCES public.cliente(id);


--
-- Name: cliente fkkpvkbjg32bso6riqge70hwcel; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT fkkpvkbjg32bso6riqge70hwcel FOREIGN KEY (id) REFERENCES public.persona(id);


--
-- PostgreSQL database dump complete
--

\unrestrict KmCM8FPgidghe18X8DtOycQHMCOMvpH5wF6gUZWW7bUDeRwCE8fmuqghZeSHQhf

